version: 2.1

orbs:
  snyk: snyk/snyk@2.2.0

jobs:
  vulnerability-scan:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run:
          name: Install packages with pip
          command: pip install -r requirements.txt
      - run:
          name: Setup Scanning
          command: |
              git config --global url."https://$GITHUB_USER:$GITHUB_TOKEN@github.com/circleci/".insteadOf "https://github.com/circleci/"
      - run:
          name: Launching Snyk Orb Scanning
          command: echo "Running snyk/scan"
      - snyk/scan:
          organization: "circleci-public"
          fail-on-issues: true
          severity-threshold: high
          monitor-on-build: false
  lint:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run:
          name: Install flake8 and Lint
          command: pip install flake8 && flake8 image-updater.py

workflows:
  lint-and-vuln-check:
    jobs:
      - vulnerability-scan:
          context: org-global-employees
      - lint