version: 2.1

orbs:
  snyk: snyk/snyk@2.2.0
  go: circleci/go@2.2.0

x-data:
  go_image: &goimage cimg/go:1.24.3

jobs:
  vulnerability-scan:
    docker:
      - image: *goimage
    steps:
      - checkout
      - run:
          name: Setup Scanning
          command: |
              git config --global url."https://$GITHUB_USER:$GITHUB_TOKEN@github.com/circleci/".insteadOf "https://github.com/circleci/"
      - run:
          name: Launching Snyk Orb Scanning
          command: echo "Running snyk/scan"
      - snyk/scan:
          organization: "circleci-public"
          fail-on-issues: true
          severity-threshold: high
          monitor-on-build: false
  lint:
    docker:
      - image: *goimage
    steps:
      - checkout
      - run:
          name: Run golangci-lint
          command: golangci-lint run --timeout=5m
  test:
    docker:
      - image: *goimage
    steps:
      - checkout
      - run:
          name: Run Go Tests
          command: go test -v ./...

workflows:
  lint-and-vuln-check:
    jobs:
      - vulnerability-scan:
          context: org-global-employees
      - lint
      - test
